### PR TITLE
Renamed to goreview-test

### PR DESCRIPTION
**Pull request by piccobit**
--- BEGIN REVIEW QUESTIONNAIRE
[X] Code
[-]  Design
[-] Test
--- END REVIEW QUESTIONNAIRE

### CODE REVIEW

**Comment by piccobit** [comment]
Testing ...

**Comment by piccobit** [comment]
Testing ...

**Comment by piccobit** [comment]
Code +1

**Comment by ursus-minor** [comment]
Yet another comments

**Comment by piccobit** [comment]
Collaborator: Review for this pull request was created. [Link to review](https://collab.stich.io/ui#review:id=4)

**Pull request closed without merging**
